server:
  port: 8088
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/saga_inventory
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
